### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by Wolvec** [apoorva-dave/LicensePlateDetector-deployment-flask#2]
Using the sames images that you recommended, gives always this error
ValueError

ValueError: Could not find a format to read the specified file in mode 'i'
Traceback (most recent call last)

    File "/home/wolvec/.local/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__

    return self.wsgi_app(environ, start_response)

    File "/home/wolvec/.local/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app

    response = self.handle_exception(e)

    File "/home/wolvec/.local/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception

    reraise(exc_type, exc_value, tb)

    File "/home/wolvec/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/home/wolvec/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app

    response = self.full_dispatch_request()

    File "/home/wolvec/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request

    rv = self.handle_user_exception(e)

    File "/home/wolvec/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception

    reraise(exc_type, exc_value, tb)

    File "/home/wolvec/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise

    raise value

    File "/home/wolvec/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request

    rv = self.dispatch_request()

    File "/home/wolvec/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request

    return self.view_functions[rule.endpoint](**req.view_args)

    File "/var/www/html/LicensePlateDetector-deployment-flask/api.py", line 67, in detectPlate

    car_image = imread(file, as_gray=True)

    File "/home/wolvec/.local/lib/python3.6/site-packages/skimage/io/_io.py", line 61, in imread

    img = call_plugin('imread', fname, plugin=plugin, **plugin_args)

    File "/home/wolvec/.local/lib/python3.6/site-packages/skimage/io/manage_plugins.py", line 210, in call_plugin

    return func(*args, **kwargs)

    File "/home/wolvec/.local/lib/python3.6/site-packages/imageio/core/functions.py", line 221, in imread

    reader = read(uri, format, "i", **kwargs)

    File "/home/.local/lib/python3.6/site-packages/imageio/core/functions.py", line 139, in get_reader

    "Could not find a format to read the specified file " "in mode %r" % mode

    ValueError: Could not find a format to read the specified file in mode 'i'

**Comment by AqsaHassan** [comment]
same issue here ... did you find any solution for this??

**Comment by TheSkrill** [comment]
Same issue.. Please help!
